name: update

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [19.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: install pnpm
        run: npm i -g pnpm
      - name: install dependencies
        run: pnpm i
      - name: run npm run upd
        run: npm run upd
      - name: commit
        run: |
          git config --global user.email dsy4567@outlook.com
          git config --global user.name dsy4567
          git add .
          git commit -m "run npm run upd" -a
      - name: GitHub Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
